### PR TITLE
Add Post Options

### PR DESCRIPTION
**Pull request by georgeh**
Add a toggle-able drawer to hold categories, tags, and a remove-site button

**Testing**

- Test data migration
    - Clear all site data
    - Deploy the `master` branch version
    - Add a site
    - Deploy this branch
    - Confirm that site displays correctly and adds categories
- Test multiple sites
    - Add tags on one site
    - Create draft
    - Add tags on second site
    - Create draft
    - Confirm no cross-polination

### CODE REVIEW

**Comment by georgeh** [comment]
@jasmussen I have categories and the expando toggle working, could I get some design <3 on this branch in the near future? 

I still have to add a "refresh site" button, get tags working, and do a refactor, so it's not a rush job.

**Comment by jasmussen** [comment]
Did a little polish, looks good now I think:

screen shot 2017-04-05 at 11 28 48

I didn't have any categories here. I'm assuming that's the "refresh site" stuff you were referring to. Also, can this be not an option? Can it be done automatically every time you open the toggle, or is it slow and error prone? If latter, totally fine that it's an option, we'll probably just show a refresh gridicon somewhere:

screen shot 2017-04-05 at 11 32 39

**Comment by georgeh** [comment]
@jasmussen I've got the tag editing in a good place, can you take a look at the Site Refresh button and any other UI elements?

One thing to note is that I removed the Google stylesheet from sidebar.html in 8d92678 since it was interfering with the category checkboxes. If you'd like to re-add it I can try to tackle the checkboxes.

**Comment by jasmussen** [comment]
Polished things up:

screen shot 2017-04-12 at 11 38 00

I didn't test with sites that have 2nd and 3rd level categories (i.e. indented), but the CSS should work for that.

**Pull request merged**
