### PR TITLE
WIP Add custom post types

### PR DESCRIPTION
**Pull request by georgeh**
This will allow users to choose a post type when creating a new draft post. 

It also hides categories & tags if they are not used by the selected post type.

Addresses #27 

# Testing

- Clear all data
- Add 2 sites with the version in master
- Save a post on site 1
- Upgrade to this version
- Confirm that post types drop-down shows on site 2
- Confirm PositionedImages work correctly
- Confirm that tags and categories hide when selecting page post type

### CODE REVIEW

**Comment by georgeh** [comment]
@jasmussen Can you take a look at the post type dropdown and see if there's a way to make it look a touch nicer?
screen shot 2017-05-01 at 2 40 03 pm

**Comment by jasmussen** [comment]
Sure thing! I'll take a look tomorrow.

**Comment by georgeh** [comment]
@jasmussen should be fixed if you pull. I'm dialing in the way we load post types the first time you open the add-on after getting upgraded to this version, guess I missed a place.

**Comment by jasmussen** [comment]
I pushed a little love to the select box. Doesn't look like I did much, but I did try putting it into extended options and then understood why you hadn't done that already. Nice work. 

screen shot 2017-05-03 at 10 49 35

**Comment by georgeh** [comment]
@jasmussen Looking at the screenshot I couldn't tell what you changed, but I could tell it feels so much better! Thank you for being an on-call magician. (I did peek at the diff to try to understand some of your design magic)

In case anyone is spelunking closed pull requests trying to find out _why post types isn't hidden away with categories and tags_: it's because you don't get to change it once the post is created. I'm OK with hiding tags and categories because they can be changed at a later date, but this needs to be clearly visible.

**Pull request merged**
